apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: captwo-sfg-7-9
  owner: captwo-sfg-7-9
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/captwo-sfg-7-9/multi-tenancy-gitops-apps.git
