apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cap1-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: cap1/environment/dev/cap1
    repoURL: https://github.com/cap1-pipeline/multi-tenancy-gitops-apps.git
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true